const state={cv:null,job:null,filter:'all'};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(message){const el=$('#toast');el.querySelector('p').textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
function syncReady(){const ready=Boolean(state.cv&&state.job);$('#analyzeButton').disabled=!ready;$('#readyDescription').textContent=ready?`${state.cv.name} sẽ được so khớp với ${state.job.name}.`:'Hãy chọn một CV và một công việc để tiếp tục.';$$('.step').forEach((step,i)=>step.classList.toggle('active',i===0||(i===1&&state.cv)||(i===2&&ready)))}
$$('.cv-option').forEach(option=>option.addEventListener('click',()=>{$$('.cv-option').forEach(x=>x.classList.remove('selected'));option.classList.add('selected');state.cv={name:option.dataset.cv};$('#selectedCvText').textContent=`Đã chọn: ${option.dataset.cv}`;syncReady()}));
$('#cvFile').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;$$('.cv-option').forEach(x=>x.classList.remove('selected'));state.cv={name:file.name};$('#selectedCvText').textContent=`Đã chọn: ${file.name}`;toast('Đã nhận CV của bạn');syncReady()});
$$('.job-option').forEach(option=>option.addEventListener('click',()=>{$$('.job-option').forEach(x=>x.classList.remove('selected'));option.classList.add('selected');state.job={name:option.dataset.job,company:option.dataset.company,score:Number(option.dataset.score)||75};syncReady()}));
function filterJobs(){const query=$('#jobSearch').value.trim().toLocaleLowerCase('vi');let visible=0;$$('.job-option').forEach(job=>{const show=(state.filter==='all'||job.dataset.category===state.filter)&&(!query||job.textContent.toLocaleLowerCase('vi').includes(query));job.hidden=!show;if(show)visible++});$('#jobEmpty').hidden=visible>0}$('#jobSearch').addEventListener('input',filterJobs);
$$('#filters button').forEach(button=>button.addEventListener('click',()=>{$$('#filters button').forEach(x=>x.classList.remove('active'));button.classList.add('active');state.filter=button.dataset.filter;filterJobs()}));
$$('.tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');const upload=tab.dataset.tab==='upload';$('#catalogPanel').hidden=upload;$('#uploadPanel').hidden=!upload}));
$('#jdFile').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;const title=$('#jobTitle').value.trim()||file.name.replace(/\.[^.]+$/,'');$$('.job-option').forEach(x=>x.classList.remove('selected'));state.job={name:title,company:'JD tải lên',score:81};$('#selectedJdText').textContent=`Đã chọn: ${file.name}`;toast('Đã nhận Job Description');syncReady()});
$('#analyzeButton').addEventListener('click',()=>{const button=$('#analyzeButton');button.disabled=true;button.textContent='Đang phân tích dữ liệu...';setTimeout(()=>{const score=state.job?.score||78;$('#scoreNumber').textContent=`${score}%`;$('#scoreRing').style.setProperty('--score',`${score*3.6}deg`);$('#scoreLabel').textContent=score>=80?'Phù hợp tốt':score>=65?'Có tiềm năng':'Cần cải thiện';$('#scoreSummary').textContent=`${state.cv.name} đáp ứng phần lớn yêu cầu cốt lõi của vị trí ${state.job.name} tại ${state.job.company}.`;$('#results').hidden=false;button.innerHTML='Phân tích mức độ phù hợp <span>→</span>';button.disabled=false;$('#results').scrollIntoView({behavior:'smooth'});toast('Phân tích CV hoàn tất')},750)});
$('#resetButton').addEventListener('click',()=>{$('#results').hidden=true;$('.workflow').scrollIntoView({behavior:'smooth'})});$('#loginButton').addEventListener('click',()=>toast('Bản giao diện demo chưa kết nối đăng nhập'));$$('.result-actions button').forEach(x=>x.addEventListener('click',()=>toast('Tính năng sẽ hoạt động khi kết nối backend')));syncReady();
