/* eslint-disable @typescript-eslint/no-explicit-any */
import React from 'react';
import { ArrowRight, Briefcase, Check, CloudUpload, FileText, Sparkles, Upload } from 'lucide-react';

export default function MatchView() {
  return <section className="app-view buddy-landing" id="view-match"><div className="match-workspace">
    <header className="match-hero"><h2 data-i18n-text="match-title">Match CV với công việc</h2><span data-i18n-text="match-description">Chọn CV và công việc. Bạn sẽ thấy phần phù hợp, điểm cần làm rõ và bằng chứng trực tiếp từ CV.</span></header>
    <div className="match-source-grid">
      <section className="match-source" id="p1-cv-card"><div className="match-source-head"><FileText size={19} /><div><p>CV CỦA BẠN</p><h3 data-i18n-text="match-cv-source">Chọn nguồn CV</h3></div></div><div className="p1-ready-banner" id="p1-cv-ready-banner"><Check size={14} /><div><strong>CV đã sẵn sàng</strong><span id="p1-cv-ready-name"></span></div><button id="p1-cv-change-btn" type="button">Đổi CV</button></div><div id="p1-cv-input-area"><div id="p1-cv-login-gate" className="p1-login-gate" style={{display:'none'}}><span>Đăng nhập để dùng CV đã lưu.</span><button id="p1-cv-login-btn" type="button">Đăng nhập</button></div><div id="p1-cv-select-section"><label htmlFor="cv-analysis-cv-select">CV đã lưu</label><select id="cv-analysis-cv-select"><option value="">Chọn CV đã lưu...</option></select></div><div className="match-source-divider">hoặc</div><form id="cv-page-upload-form"><input id="cv-page-title-input" hidden /><label className="match-upload" id="cv-dropzone"><CloudUpload size={27} /><strong>Upload CV tạm thời</strong><span>PDF hoặc DOCX · tối đa 10 MB</span><input id="cv-page-file-input" type="file" accept=".pdf,.docx" hidden /></label><span id="selected-file-name"></span><button id="btn-page-do-upload" type="submit" hidden>Upload</button></form></div></section>
      <section className="match-source" id="p1-jd-card"><div className="match-source-head"><Briefcase size={19} /><div><p>JOB DESCRIPTION</p><h3 data-i18n-text="match-jd-source">Thêm JD của bạn</h3></div></div><div className="p1-ready-banner" id="p1-jd-ready-banner"><Check size={14} /><div><strong>Job Description đã sẵn sàng</strong><span id="p1-jd-ready-name"></span></div><button id="p1-jd-change-btn" type="button">Đổi JD</button></div><div id="p1-jd-input-area"><div className="match-tabs" role="tablist"><button id="p1-job-explore-tab" type="button" role="tab" aria-selected="true" data-i18n-text="match-tab-catalog">Chọn Job có sẵn</button><button id="p1-job-upload-tab" type="button" role="tab" aria-selected="false" data-i18n-text="match-tab-upload">Upload JD</button></div><div id="p1-job-explore-panel"><input id="p1-job-search" type="search" placeholder="Tìm theo chức danh hoặc kỹ năng..." /><div id="p1-job-filters" className="match-filters"><button data-job-filter="AI" type="button">AI</button><button data-job-filter="Backend" type="button">Backend</button><button data-job-filter="Frontend" type="button">Frontend</button><button data-job-filter="Data" type="button">Data</button><button data-job-filter="DevOps" type="button">DevOps</button></div><p id="p1-job-count"></p><div id="p1-job-grid" className="p1-job-grid"></div><div id="p1-job-empty" hidden>Chưa có công việc phù hợp. <button id="p1-job-empty-upload" type="button">Tải JD riêng</button></div></div><div id="p1-job-upload-panel" hidden><div id="p1-jd-login-gate" className="p1-login-gate" style={{display:'none'}}><span>Đăng nhập để lưu JD riêng.</span><button id="p1-jd-login-btn" type="button">Đăng nhập</button></div><div id="p1-jd-select-section" hidden><select id="cv-analysis-jd-select"><option value="">Chọn JD đã lưu</option></select></div><form id="cv-jd-upload-form"><input id="cv-jd-title-input" placeholder="Tên vị trí (tuỳ chọn)" /><label className="match-upload" id="cv-jd-dropzone"><Upload size={25}/><strong>Upload Job Description</strong><span id="cv-jd-file-name">PDF, DOCX, TXT hoặc ảnh</span><input id="cv-jd-file-input" type="file" accept=".pdf,.docx,.txt,image/*" hidden /></label><button type="submit">Dùng JD này để phân tích</button></form></div></div></section>
    </div>
    <section className="match-ready" id="p1-cta-area"><div><Sparkles size={18}/><strong data-i18n-text="match-ready">Sẵn sàng để Match</strong><span id="p1-cta-hint">Chọn CV và công việc để bắt đầu.</span></div><button id="p1-analyze-btn" type="button"><Sparkles size={17}/><span data-i18n-text="match-analyze"> Phân tích Match</span></button></section>
    <section id="p1-analysis-journey" className="p1-analysis-journey" hidden aria-live="polite"><h3 id="p1-analysis-title">AI đang đối chiếu CV và công việc</h3><p id="p1-analysis-supporting">Kết quả dựa trên bằng chứng trong CV, không chỉ từ khóa.</p><p id="p1-analysis-cv-label"></p><p id="p1-analysis-jd-label"></p><p id="p1-analysis-insight-title"></p><p id="p1-analysis-insight-body"></p><p id="p1-analysis-error" hidden>Không thể hoàn tất phân tích. <button id="p1-analysis-retry">Thử lại</button></p></section>
    <section id="cv-analysis-results-card" className="match-summary" hidden><div id="cv-analysis-empty-state"></div><div id="cv-analysis-result-content" hidden>
      <header className="match-result-overview"><div className="cv-result-score-ring"><strong id="cv-result-match-score">—</strong><span>Match score</span></div><div className="cv-result-summary-block"><p id="cv-result-context"></p><h3>Kết quả đánh giá</h3><p id="cv-result-summary"></p><div id="cv-result-confidence-summary" className="cv-result-confidence-summary"></div></div></header>
      <div className="cv-result-skills-grid"><section className="cv-result-panel is-positive"><h4>✓ Điểm phù hợp nổi bật</h4><div id="cv-result-matching-skills" className="cv-result-tags"></div></section><section className="cv-result-panel is-attention"><h4>! Cần làm rõ hoặc bổ sung</h4><div id="cv-result-missing-skills" className="cv-result-tags"></div><div id="cv-result-partial-skills" className="cv-result-tags"></div></section></div>
      <section className="cv-result-priority-panel"><div><h4>Ưu tiên cải thiện</h4><p>Chỉ dựa trên yêu cầu JD và evidence trong CV của bạn.</p></div><div id="cv-result-priority-actions" className="cv-result-action-list"></div></section>
      <section className="cv-result-detail-panel"><h4>Điểm theo tiêu chí</h4><div id="cv-result-score-breakdown" className="cv-result-score-breakdown"></div><div id="cv-result-criteria" className="cv-result-criteria-list"></div></section>
      <div id="cv-result-warnings" className="cv-result-warnings"></div>
      <div className="match-result-actions"><button id="btn-open-full-gap-result" type="button">Xem Gap Analysis chi tiết <ArrowRight size={15}/></button><button id="btn-compare-multi-position" type="button">Match với Job khác</button><button id="btn-start-interview-from-analysis" type="button">Luyện phỏng vấn voice</button></div>
      <div id="cv-result-requirement-evidence" hidden></div><div id="cv-result-soft-skills" hidden></div><div id="cv-result-learning-actions" hidden></div><div id="cv-result-section-recommendations" hidden></div><div id="cv-result-certifications" hidden></div><div id="cv-result-projects" hidden></div><div id="cv-result-suggestions-preview" hidden></div><div id="cv-result-guardrail-status" hidden></div>
    </div></section>
  </div></section>;
}
